name: talktranslate
description: "TalkTranslate v2 — VoIP 实时翻译通话"
publish_to: 'none'
version: 2.0.2+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_webrtc: ^0.12.0
  web_socket_channel: ^3.0.0
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  uuid: ^4.3.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  http: ^1.2.0
  flutter_overlay_window: ^0.4.0
  flutter_secure_storage: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0

flutter:
  uses-material-design: true
